### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by kirides** [bram-prins/flyff-universe-quest-rewards-overview#1]
i currently use a stylebot css override for dark theme and would like if the site could support dark themes natively.

```css
@media(prefers-color-scheme:dark) {
  body {
  background: #1e1e1e;
  color: #fff;
  }

  a {
    color: #aaa;
  }

  table {
    border: #5e5e5e solid 2px;
    background: #1e1e1e;
  }
  thead tr {
      background: #2e2e2e;
  }
  tbody tr:nth-child(even) {
      background: #2e2e2e;
  }
}

```

![image](https://user-images.githubusercontent.com/13602143/201360251-f27a189a-9173-4d79-a495-eec0b41766e1.png)
